version: '3.1'

services:
  redis:
    restart: always
    container_name: compose_redis
    image: redis
  mongo:
    image: mongo
    restart: always
    container_name: compose_mongodb
    ports:
      - '27017:27017'
    volumes:
      - 'mongodata:/data/db'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
  mongo-express:
    image: mongo-express
    restart: always
    container_name: compose_mongodb_express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password

volumes:
  mongodata:
    driver: local
    driver_opts:
      type: none
      device: /Volumes/Second_Disk/data/docker/mongodata/
      o: bind
